services:
  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'ok'
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '127.0.0.1:${DATABASE_EXTERNAL_PORT}:3306'

  pma:
    image: phpmyadmin
    environment:
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '127.0.0.1:${PMA_EXTERNAL_PORT}:80'
